language: node_js
node_js:
- 8.11.4
services:
- rabbitmq
- memcached
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - rabbitmq-server
cache:
  directories:
  - node_modules
before_install:
- export CXX="g++-4.8"
before_script:
- npm install -g npm@6.2.0
- npm install -g audit-filter
script:
- npm audit --json | audit-filter --nsp-config=.nsprc --audit=-
- npm test
deploy:
  provider: npm
  email: cloudservices@loyalty.co.nz
  api_key:
    secure: nQSdbTHXP9V3k+WYiIVtYfas4Udge/RM4Z+xJJAN89ywPwMqB0nZG1ugo5gvSOmgpI/lf+euf+GBYLhBgGV1Uqc2/y2f6RdLk8KaxUg6b0Jq45FvlZgfsQVoHf+v7J5Z+vHefiquzbvSllafWBD8W2DgWv5Xc+SOC+VxoKQ0i1TLw19/6Y7Kfz/W+bSGVVSghUkloyxSHXkDCHKnSXQ9RNt5zU5Z9vUgxlBnieB4OYWvB+SWBKugM0PtikCIxwNeKzNrSPd8fx170OZrSOywzAlFxP7Utev15IDMrG6azIaEk7tKkp4ZxEmlS/Y8WjouKx1SrYyoxFnKVI/pdvor7571fcFbHBtOaEQiddKAH+r1ohKJFWs0mum6MCkdF7VV7XrMMXT2FyGcu97Y1vzh26T0xd8J0yD6zrzEuj7OmnjE2Zhm7LXbxAG/MOaxoOUc8DLt/NkSyZwczSSYPVXrkt1tDua21PdPXAtVDml4hIDZsEhRdHj3Zn0yWhOByu8R6B6vqftKTklzpjZyxCXfefVHBEOQfdHrhZIRSu6d5atwa98D6qew7SlCmbZsB+Q3caLfWeorjNEvE5zEa5IevoeSnjLg8l94xWsTrxqn2uFv8oLAKJbsHHEC3fsbzgKYfYBKTmRdCS2CNr7UK1ieeV/FaNmRESSdlKRdz7Y8nRQ=
  on:
    tags: true
