[[IgnoredVulns]]
id = "GHSA-gxpj-cx7g-858c"

[[IgnoredVulns]]
id = "GHSA-2j2x-2gpw-g8fm"

[[IgnoredVulns]]
id = "GHSA-f8q6-p94x-37v3"

[[IgnoredVulns]]
id = "GHSA-p8p7-x288-28g6"

[[IgnoredVulns]]
id = "GHSA-72xf-g2v4-qvf3"