name: Node.js CI

on: [pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
  
      services:
        rabbitmq:
          image: rabbitmq
          ports:
            - 5672:5672
        memcached:
          image: memcached
          ports:
            - 11211:11211
  
      steps:
        - uses: actions/checkout@v2
  
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '8.11.4'
            cache: 'npm'
  
        - name: Install default GCC and G++
          run: sudo apt-get update && sudo apt-get install -y gcc g++
  
        - name: Set environment variable CXX to g++
          run: echo "CXX=g++" >> $GITHUB_ENV
  
        - name: Install npm@6.2.0
          run: npm install -g npm@6.2.0
  
        - name: Install audit-filter globally
          run: npm install -g audit-filter

        - name: Install dependencies
          run: npm install
  
        # - name: Audit dependencies
        #   run: npm audit --json | audit-filter --nsp-config=.nsprc --audit=-
  
        - name: Run tests
          run: npm test
  
  
  
